apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: externalgroups.multicluster.linkerd.io
  annotations:
    {{ include "partials.annotations.created-by" . }}
  labels:
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    linkerd.io/control-plane-ns: {{.Release.Namespace}}
spec:
  group: multicluster.linkerd.io
  names:
    categories:
    - external
    kind: ExternalGroup
    listKind: ExternalGroupList
    plural: externalgroups
    singular: externalgroup
    shortNames: [eg]
  scope: Namespaced
  versions:
  - name: v1alpha1
    served: true
    storage: true
    schema:
      openAPIV3Schema:
        type: object
        description: beep boop alien workload
        properties:
          apiVerson:
            description: "APIVersion defines versioned schema"
            type: string
          kind:
            description: "Kind is the kind"
            type: string
          metadata:
            type: object
          spec:
            type: object
            properties:
              template:
                type: object
                description: endpoint template
                properties:
                  expectedIdentity:
                    type: string
                    description: "Catch all for identity to bootstrap everything else"
              ports:
                type: array
                items:
                  type: object
                  properties:
                    port:
                      description: "Name of the port to target"
                      format: int32
                      maximum: 65535
                      minimum: 1
                      type: integer
                    protocol:
                      description: "Protocol"
                      type: string
          status:
            type: object
            properties:
              conditions:
                type: array
                items:
                  type: object
                  properties:
                    lastProbeTime:
                      type: string
                    lastTransitionTime:
                      type: string
                    status:
                      type: string
                    type:
                      type: string
                    reason:
                      type: string
                    message:
                      type: string



