---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: externalendpoints.multicluster.linkerd.io
  annotations:
    {{ include "partials.annotations.created-by" . }}
  labels:
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    linkerd.io/control-plane-ns: {{.Release.Namespace}}
spec:
  group: multicluster.linkerd.io
  names:
    categories:
    - external
    kind: ExternalEndpoint
    listKind: ExternalEndpointList
    plural: externalendpoints
    singular: externalendpoint
    shortNames: [ee]
  scope: Namespaced
  versions:
  - name: v1alpha1
    served: true
    storage: true
    schema:
      openAPIV3Schema:
        type: object
        description: beep boop alien workload
        properties:
          apiVerson:
            description: "APIVersion defines versioned schema"
            type: string
          kind:
            description: "Kind is the kind"
            type: string
          metadata:
            type: object
          spec:
            type: object
            properties:
              workloadIPs:
                type: array
                description: endpoint addresses
                items:
                  type: object
                  properties:
                    ip:
                      description: "IP (as a string for now)"
                      type: string
              ports:
                type: array
                items:
                  type: object
                  properties:
                    port:
                      description: "Name of the port to target"
                      format: int32
                      maximum: 65535
                      minimum: 1
                      type: integer
                    protocol:
                      description: "Protocol"
                      type: string
              identity:
                type: string
              serverName:
                type: string
          status:
            type: object
            properties:
              conditions:
                type: array
                items:
                  type: object
                  properties:
                    lastProbeTime:
                      type: string
                    lastTransitionTime:
                      type: string
                    status:
                      type: string
                    type:
                      type: string
                    reason:
                      type: string
                    message:
                      type: string
---
