[workspace]
resolver = "2"
members = [
    "policy-controller",
    "policy-controller/core",
    "policy-controller/grpc",
    "policy-controller/k8s/api",
    "policy-controller/k8s/index",
    "policy-controller/k8s/status",
    "policy-controller/runtime",
    "policy-test",
]

[profile.release]
lto = "thin"

[workspace.dependencies]
k8s-openapi = { version = "0.24", features = ["v1_31"] }
kube = { version = "0.98", default-features = false }
kubert = { version = "0.23.0-alpha5", default-features = false }

# TODO(ver): Remove this once we update to a proper generated version of the gateway api bindings.
k8s-gateway-api = { git = "https://github.com/linkerd/k8s-gateway-api-rs", features = [
    "experimental",
] }
