---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: serviceimports.multicluster.linkerd.io
  annotations:
    {{ include "partials.annotations.created-by" . }}
  labels:
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    linkerd.io/control-plane-ns: {{.Release.Namespace}}
spec:
  group: multicluster.linkerd.io
  names:
    categories:
    - multicluster
    kind: ServiceImport
    listKind: ServiceImportList
    plural: serviceimports
    singular: serviceimport
    shortNames: []
  scope: Namespaced
  versions:
  - name: v1alpha1
    served: true
    storage: true
    schema:
      openAPIV3Schema:
        description: >-
          A ServiceImport describes services imported in a cluster agnostic way
        type: object
        required: [spec]
        properties:
          apiVerson:
            type: string
          kind:
            type: string
          metadata:
            type: object
          spec:
            type: object
            properties:
              ports:
                type: array
                description: ports describes a list of ports exposed by the
                  workload
                items:
                  properties:
                    name:
                      type: string
                      description: name must be an IANA_SVC_NAME and unique
                        within the ports set. Each named port can be referred
                        to by services.
                    port:
                      format: int32
                      maximum: 65535
                      minimum: 1
                      type: integer
                    protocol:
                      description: protocol exposed by the port. Must be UDP or
                        TCP. Defaults to TCP.
                      type: string
                      default: "TCP"
                  type: object
                  required:
                  - port
              type:
                description: type of svc
                type: string
          status:
            type: object
            properties:
              clusters:
                type: array
                items:
                  type: string

